#===========================================================================
# DO NOT MANUALLY EDIT THIS FILE
#
# This is the master settings file, in which all defaults are held.
# These are merged with the user's settings each time the game is loaded.
# The user settings are created by the game and saved to the main directory
# when anything changes.
#===========================================================================
---
levels:
  0: # Test track for development purposes.
    normal:
      high-score: 0
      high-scorer: ???
      finished: false
    hardcore:
      high-score: 0
      high-scorer: ???
      finished: false

  1: # Tutorial track.
    normal:
      high-score: 0     # Highest score, whether finished the level or not.
      high-scorer: ???  # Name of person getting the high score.
      finished: false   # Has the player ever finished the level?
    hardcore:
      high-score: 0     # Highest score, whether finished the level or not.
      high-scorer: ???  # Name of person getting the high score.
      finished: false   # Has the player ever finished the level?

  2:
    normal:
      high-score: 0
      high-scorer: ???
      finished: false
    hardcore:
      high-score: 0
      high-scorer: ???
      finished: false

  3:
    normal:
      high-score: 0
      high-scorer: ???
      finished: false
    hardcore:
      high-score: 0
      high-scorer: ???
      finished: false

graphics:
  scaling: 8 # Multiple of the underlying window size (Game sort of runs at 96x60, though some things are at a different scale)
  fullscreen: false

sound: {}

gameplay:
  selected_cat: :zed
  hardcore: false

key_controls:
  general: # Controls that aren't specifically for either player.
    pause: :p
    screenshot: :f12

  players:
    zed: # Player one controls.
      left: :a
      right: :d
      up: :w
      down: :s
      jump: :space

    ginger: # Player two controls.
      left: :left
      right: :right
      up: :up
      down: :down
      jump: :return
