#===========================================================================
# DO NOT MANUALLY EDIT THIS FILE
#
# This is the master settings file, in which all defaults are held.
# These are merged with the user's settings each time the game is loaded.
# The user settings are created by the game and saved to the main directory
# when anything changes.
#===========================================================================
---
version: 0.3.0

levels: {} # Generated as needed.

graphics:
  scaling: 8 # Multiple of the underlying window size (Game sort of runs at 96x60, though some things are at a different scale)
  fullscreen: false

sound:
  effects_volume: 50
  music_volume: 50

gameplay:
  selected_cat: :zed
  hardcore: false
  inversion: false
  selected_level:
    normal: 1
    hardcore: 1
    hardcore_inversion: 1
    inversion: 1

general:
  auto_show_intro: true

key_controls:
  general: # Controls that aren't specifically for either player.
    pause: :p
    screenshot: :f12
    show_fps: :f11

  players:
    zed: # Player one controls.
      left: :a
      right: :d
      up: :w
      down: :s
      jump: :space

    ginger: # Player two controls.
      left: :left
      right: :right
      up: :up
      down: :down
      jump: :return
