---

time_limit: 50.0

wall:
  tiles: |
    --------------------L--L----------------f----------
    ---------------##---L##L--x-x--###------f----------
    --------------------L--L----------------f----------

  default_tile: [0, 0]

floor:
  tiles: |
    ------------------ssssssssssssssssss----f----------
    ------------------ssssssssssssssssss----f----------
    ------------------XXXXXssssssssssssss---f----------
    ----------------------------------------f----------
    ------------------rrrrrrrrrrrrrrrrr-----f----------

  default_tile: CheckeredFloor

messages: []