---

time_limit: 50.0

wall: |
  ----------L--L----------------f----------
  -----##---L##L--x-x--###------f----------
  ----------L--L----------------f----------


floor: |
  ----------L--l-{-sSsSSSs-->>\-f----------
  ----------L--l---s-sss-s--/-\-f----------
  ----------L--l-BXsss-sss--/<<-f----------
  ----------L--l---s-sss-s------f----------
  ----------L--l---sssssss-}----f----------