---

time_limit: 50.0

wall:
  tiles: |
    ----------L--L----------------f----------
    -----##---L##L--x-x--###------f----------
    ----------L--L----------------f----------

  default_tile: [0, 0]

floor:
  tiles: |
    -------^eeL--l-{-sSsSSSs-->>\-f----------
    -------^--L--l---s-sss-s--/-\-f----------
    -------^--L--l-BXsss-sss--/<<-f----------
    -------^--L--l---s-sss-s------f----------
    -------^EEL--l---sssssss-}----f----------

  default_tile: CheckeredFloor