---

time_limit: 50.0

wall:
  tiles: |
    ----------------------------------------f----------
    ---------------##----##---x-x--###------f----------
    ----------------------------------------f----------

  default_tile: [0, 0]

floor:
  tiles: |
    ----------------------------------------f----------
    ----------------------------------------f----------
    ----------------------------------------f----------
    ----------------------------------------f----------
    ----------------------------------------f----------

  default_tile: CheckeredFloor

messages: []