---

time_limit: 50.0

wall: |
  ------------------------------f----------
  -----##----###--x-x--###------f----------
  ------------------------------f----------


floor: |
  ---------------{-sSsSSSs-->>\-f----------
  -----------------s-sss-s--/-\-f----------
  ---------------B-sss-sss--/<<-f----------
  -----------------s-sss-s------f----------
  -----------------sssssss-}----f----------