---

time_limit: 20.0

wall: |
  -----------------#####---#####------------------------------------------------------------------------------------------------------------------------------
  ------###---x----#####---#####-----o-o-o-----###----x---###-------###------###-x----###--------###-------###------###------###--------###--x-x--###------###
  ------------------------------------------------------------------------------------------------------------------------------------------------------------


floor: |
  ...................s.........s....___.......^ssss.........s.........s.................ss.................sssssssss..........ss....ss....ss.......ss.........
  ...................s.........s....___.......^ssss.........s.........s....___..........ss.........sss......sssssss...........ss....ss....ss.......ss.........
  ...................s.........s....___.......^ssss.........s.........s....___..........ss........sssss......sssss............ss....ss....ss.......ss.........
  .............................s....___.......^ssss.........s.........s....___..........ss.......sssssss......sss.............ss....ss....ss.......ss.........
  .............................s....___.......^ssss.........s.........s.................ss......sssssssss.....................ss....ss....ss.......ss.........
  ============================================================================================================================================================

#  Wall key:
#    - wall
#    # square window
#    x tech panel
#    o porthole
#
#  Floor key:
#    . StandardFloor
#    _ GlassFloor (window)
#    s SlowFloor
#    = PipesFloor
#    ^ Std + Spring