---

time_limit: 20.0

wall: |
  -----------------#####---#####------------------------------------------------------------------------------------------------------------------------------
  ------###---x----#####---#####-----o-o-o-----###----x---###-------###------###-x----###--------###-------###------###------###--------###--x-x--###------###
  ------------------------------------------------------------------------------------------------------------------------------------------------------------


floor: |
  ...................s.........s..................s.........s.........s..................s...................sssss..............s.........s.........s.........
  ...................s.........s..................s.........s.........s..................s...................sssss..............s.........s.........s.........
  ...................s.........s..................s.........s.........s..................s........sssss......sssss..............s.........s.........s.........
  ...................s.........s..................s.........s.........s..................s........sssss.........................s.........s.........s.........
  ...................s.........s..................s.........s.........s..................s........sssss.........................s.........s.........s.........
  ============================================================================================================================================================

key: |
  Wall key:
    - wall
    # square window
    x tech panel
    o porthole

  Floor key:
    . BasicFloor
    s SlowFloor
    = PipesFloor
