---

time_limit: 24.0

wall: |
  -----------------#####---#####------###---------------------------------------------------------------------------------------------------------------f-------
  ------###---x----#####---#####------###------###--xxxx--###-------###------###-x----###------o-o-o-----###------###------###----o-o-o----x-x--###-----f-------
  ------------------------------------###---------------------------------------------------------------------------------------------------------------f-------


floor: |
  -------------------s-----b-----S----###-------^sSss^----^---s---------s--------------b--SS--p------------sSssSSSss----------sS-----SsSsss-----ss------f-------
  -------------------s----b------s----###-------^ssss---------s---------s-----###------b--ss---------sss----sssssss-----------ss-----ssssss-----ss------f-------
  -------------------s---b-------s----###-------^ssss---------s---------s----r###r-----b--ss--------sssss----sssss----------B-ssssssss----ssssssss------f-------
  ------------------------b------s----###-------^ssss---------s---------s-----###------b--ss-------sssssss----sss-------------ssssssss----ssssssss------f-------
  -------------------------b-----s----###-------^ssss---------s---------s--------------b--ss------sssssssss-------------------ssssssssssssssssssss------f-------

#  Wall key:
#    - wall
#    # square glass window
#    x tech panel
#    o porthole
#
#  Floor key:
#    - StandardFloor
#    # GlassFloor (window)
#    f FinishFloor
#    s SlowFloor
#    = PipesFloor
#    ^ Std + Spring
#    b Std + Barrel
#    B Std + Board
#    m Std + MessageScreen (on wall)
#    S Std + SlowSplat (goo on wall)
#    > Forward Teleporter
#    < Backward Teleporter