---

time_limit: 24.0

wall: |
  -----------------#####---#####------------------------------------------------------------------------------------------------------------------------f-------
  ------###---x----#####---#####-----o-o-o-----###--xxxx--###-------###------###-x----###--------###-----###------###------###--------###--x-x--###-----f-------
  ------------------------------------------------------------------------------------------------------------------------------------------------------f-------


floor: |
  ...................s.....b.....s....___.......^ssss^....^...s.........s..............b..ss..p............sssssssss..........ss.....ssssss.....ss......f.......
  ...................s....b......s....___.......^ssss.........s.........s....___.......b..ss.........sss....sssssss...........ss.....ssssss.....ss......f.......
  ...................s...b.......s....___.......^ssss.........s.........s...r___r......b..ss........sssss....sssss..........B.ssssssss....ssssssss......f.......
  ........................b......s....___.......^ssss.........s.........s....___.......b..ss.......sssssss....sss.............ssssssss....ssssssss......f.......
  .........................b.....s....___.......^ssss.........s.........s..............b..ss......sssssssss...................ssssssssssssssssssss......f.......

#  Wall key:
#    - wall
#    # square window
#    x tech panel
#    o porthole
#
#  Floor key:
#    . StandardFloor
#    _ GlassFloor (window)
#    f FinishFloor
#    s SlowFloor
#    = PipesFloor
#    ^ Std + Spring
#    b Std + Barrel
#    B Std + Board