---

time_limit: 36

wall:
  tiles: |
    ----oo----o----------oo--------o---------o--------------o-----------------o-------------------------o---o----------------o------------------------------f----------
    ---x----------------------------------------------x-----------------------------------------------------------------------------------------------------f----------
    --------------------------x-----------------------------------------------------------------------------------------------------------------------------f----------

  default_tile: [0, 0]

floor:
  tiles: |
    --S--------------m-----m-----m-----m-----m----m-------m-sssm------m--s----s-----m----m----m-----------m--b---p-------p------m{p--------m--{>>>>>--m----mf---m------
    --------------------------------------------------------sss----------s----s-----------rrrrrrrrr----------b-------------------{-p----XXXXXXXX->>>>>------f----------
    --------------------------------------------------------sss----------s----s-----------rrrrrrrrr----------b-------------------{--p---XXXXXXXXX-->>>>>----f----------
    --------------------------------------------------------sss----------s----s-----------rrrrrrrrr----------b-------------------{---p---------}XX--->>>>>--f----------
    --------------------------------------------------------sss----------s----s------------------------------b-------p-----------{----p}-------}XXX---->>>>>f----------

  default_tile: CheckeredFloor

# Messages can be up to 14 chars (15 if there is a follow-on screen) and must have 4+ spaces between them.
# - '0123456789012345'
messages:
  - 'Right: <%right%>'
  - 'Left: <%left%>'
  - 'Up: <%up%>'
  - 'Down: <%down%>'

  - ' You have to run'
  - 'this way =====>'

  - '  Green-goo will'
  - 'slow you down  '

  - 'Jump: <%jump%>'

  - '  Get extra time'
  - 'by pouncing on  '
  - 'GIANT RATOIDS! '

  - 'Avoid enemies! '

  - 'Teleport forward'
  - '   or backward!'

  - '           Cross'
  - 'the line as fast'
  - 'as you can!    '
