---

time_limit: 20.0

wall: |
  -----------------#####---#####--------------------------------------------------------------------------------------------------------------------------------
  ------###---x----#####---#####-----o-o-o-----###--xxxx--###-------###------###-x----###--------###-------###------###------###--------###--x-x--###------###--
  --------------------------------------------------------------------------------------------------------------------------------------------------------------


floor: |
  ...................s.....b.....s....___.......^ssss^....^...s.........s..............b..ss.................sssssssss..........ss....ss....ss.......ss.........
  ...................s....b......s....___.......^ssss.........s.........s....___.......b..ss.........sss......sssssss...........ss....ss....ss.......ss.........
  ...................s...b.......s....___.......^ssss.........s.........s....___.......b..ss........sssss......sssss............ss....ss....ss.......ss.........
  ........................b......s....___.......^ssss.........s.........s....___.......b..ss.......sssssss......sss.............ss....ss....ss.......ss.........
  .........................b.....s....___.......^ssss.........s.........s..............b..ss......sssssssss.....................ss....ss....ss.......ss.........

#  Wall key:
#    - wall
#    # square window
#    x tech panel
#    o porthole
#
#  Floor key:
#    . StandardFloor
#    _ GlassFloor (window)
#    s SlowFloor
#    = PipesFloor
#    ^ Std + Spring
#    b Std + Barrel