---

time_limit: 24.0

wall:
  tiles: |
    ---------------------------#####---#####------###---------------------------------------------------------------------------------------------------------------f----------
    --######-----##-------x----#####---#####------###------###--xxxx--###-------###------###-x----###------o-o-o-----###------###------###----o-o-o----x-x--###-----f----------
    ----------------------------------------------###---------------------------------------------------------------------------------------------------------------f----------

  default_tile: [0, 0]

floor:
  tiles: |
    --sss------------m-----------s-----b-----s----###-------^ssss^----^---s---------s--------------b--ss--p------------sssssssss----------ss-----ssssss-----ss------f----------
    --s-s------------------------s----b------s----###-------^ssss---------s---------s-----###------b--ss---------sss----sssssss-----------ss-----ssssss-----ss------f----------
    -----------------------------s---b-------s----###-------^ssss---------s---------s----r###r-----b--ss--------sssss----sssss------X---B-ssssssss----ssssssss------f----------
    ----------------------------------b------s----###-------^ssss---------s---------s-----###------b--ss-------sssssss----sss-------------ssssssss----ssssssss------f----------
    -------ss--------------------------b-----s----###-------^ssss---------s---------s--------------b--ss------sssssssss-------------------ssssssssssssssssssss------f----------

  default_tile: CheckeredFloor

# Messages can be up to 14 chars (15 if there is a follow-on screen) and must have 4+ spaces between them.
# - '0123456789012345'
messages:
  - "No running!     "