---

time_limit: 24.0

wall: |
  -----------------#####---#####------###---------------------------------------------------------------------------------------------------------------f----------
  ---##-------x----#####---#####------###------###--xxxx--###-------###------###-x----###------o-o-o-----###------###------###----o-o-o----x-x--###-----f----------
  ------------------------------------###---------------------------------------------------------------------------------------------------------------f----------

floor: |
  -------m-----------s-----b-----S----###-------^sSss^----^---s---------s--------------b--SS--p------------sSssSSSss----------sS-----SsSsss-----ss------f----------
  -------------------s----b------s----###-------^ssss---------s---------s-----###------b--ss---------sss----sssssss-----------ss-----ssssss-----ss------f----------
  -------------------s---b-------s----###-------^ssss---------s---------s----r###r-----b--ss--------sssss----sssss------X---B-ssssssss----ssssssss------f----------
  ------------------------b------s----###-------^ssss---------s---------s-----###------b--ss-------sssssss----sss-------------ssssssss----ssssssss------f----------
  -------------------------b-----s----###-------^ssss---------s---------s--------------b--ss------sssssssss-------------------ssssssssssssssssssss------f----------

# Messages can be up to 14 chars (15 if there is a follow-on screen) and must have 4+ spaces between them.
# - '0123456789012345'
messages:
  - "No racing!     "