---

time_limit: 24.0

wall: |
  -------------------------------------------L--L--L--L--L-------------------------------------------------------------------------------------------------------f----------
  -------------------------------------------L--L--L--L--L-------------------------------------------------------------------------------------------------------f----------
  -------------------------------------------L--L--L--L--L-------------------------------------------------------------------------------------------------------f----------

floor: |
  ---------->>>>>>>>>>>>>>>>>>>\\X-----------l--Lr-l--L--l--------------------------------------------------------------------------f----------
  ---------->>>>>>>>>>>>>>>>>>>\\X-----------l--L--l--L--l--------------------------------------------------------------------------f----------
  ----------//-----X-----X-----\\------------l--L--lr-L--l--------------------------------------------------------------------------f----------
  ----------//<<<<<<<<<<<<<<<<<<<------------l--L--l--L--l--------------------------------------------------------------------------f----------
  ----------//<<<<<<<<<<<<<<<<<<<------------l--L--l--Lr-l--------------------------------------------------------------------------f----------

# Messages can be up to 14 chars (15 if there is a follow-on screen) and must have 4+ spaces between them.
# - '0123456789012345'
messages:
  - "Don't drink Ille"
  - "gal Space Beer!"