---

time_limit: 35

wall:
  tiles: |
    -----------------------------------------------L--L--L--L-xL-----------ooo----------------L-----------------------------------LL--LL----------f----------
    -------------------oo-------oo--------oo-------Lx-L--LxxL--Lx----oo----ooo-------oo-------Lx--------oo-----oo-----oo----------LLxxLL------oo--f----------
    --------------x-------------------x------------Lx-L-xL--Lx-L-----------ooo----------------L-------------x---------------------LLx-LLx---------f----------

  default_tile: [6, 0]

floor:
  tiles: |
    eEeee--m------>>>>>>>>>>>>>>>>>>>\\X-----------l--Lr-l--L--l-------r-------eeeeeeeer------L-------sseesseesseesseEsseess------ll--LL----------f----------
    eeeEE--------->>>>>>>>>>>>>>>>>>>\\X-----------l--L--l--L--l--------ss-----eeeeeeee-------L-------ss--ss--ss--ssr-ss--ss------ll-XLL----------f----------
    eeEee---------//-----X--r--X-----\\------------l--L--lr-L--l-------ssss-----mr---m--------L-------ss--ss--ssr-ss--ssr-ss------ll--LL--------e-f----------
    eeeee---------//<<<<<<<<<<<<<<<<<<<------------l--L--l--L--l--------ss-----EEEEEEEE-------L-------ssr-ssr-ss--ss--ss--ss------ll--LL----------f----------
    eEeeE--------r//<<<<<<<<<<<<<<<<<<<------------l--L--l--Lr-l---------------EEEEEEEE-------L-------sseesseEsseesseesseess------ll--LL----------f----------

  default_tile: MetalFloor

# Messages can be up to 14 chars (15 if there is a follow-on screen) and must have 4+ spaces between them.
# - '0123456789012345'
messages:
  - "The Foundry   "

  - "Don't drink Ille"
  - "gal Space Beer!"