---

time_limit: 35

wall: |
  -----------------------------------------------L--L--L--L-xL------------ooo---------------L------------------------------LL--LL----------f----------
  -------oo----------oo-------oo--------oo-------Lx-L--LxxL--Lx----oo-----ooo------oo-------Lx--------oo---oo----oo--------LLxxLL------oo--f----------
  --------------x-------------------x------------Lx-L-xL--Lx-L------------ooo---------------L------------------------------LLx-LLx---------f----------

floor: |
  eEeee--------->>>>>>>>>>>>>>>>>>>\\X-----------l--Lr-l--L--l-------r-------eeeeeeeer------L-------ssessessessessess------ll--LL----------f----------
  eeeEE--------->>>>>>>>>>>>>>>>>>>\\X-----------l--L--l--L--l--------ss-----eeeeeeee-------L-------ss-ss-ss-ssrssrss------ll-XLL----------f----------
  eeEee---------//-----X--r--X-----\\------------l--L--lr-L--l-------ssss-----mr---m--------L-------ss-ss-ssrss-ss-ss------ll--LL--------e-f----------
  eeeee---------//<<<<<<<<<<<<<<<<<<<------------l--L--l--L--l--------ss-----EEEEEEEE-------L-------ssrssrss-ss-ss-ss------ll--LL----------f----------
  eEeeE--------r//<<<<<<<<<<<<<<<<<<<------------l--L--l--Lr-l---------------EEEEEEEE-------L-------ssessessessessess------ll--LL----------f----------

# Messages can be up to 14 chars (15 if there is a follow-on screen) and must have 4+ spaces between them.
# - '0123456789012345'
messages:
  - "Don't drink Ille"
  - "gal Space Beer!"