---

time_limit: 30

wall:
  tiles: |
    ---------o---o---o--------------o-------o-----------------------o--------o------------------x-----oooo--------------------------------o----------------o------o---f----------
    --x---------------------------------------------------------------------x--x--------------------------------------oo----------------------------------------------f----------
    --------------------------x--------x---------------------------------------------------------------------xxxx---------------------------x-------------------------f----------

  default_tile: [4, 1]

floor:
  tiles: |
    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>\\\\\\\\\\-gg-rl-------------->>>>>>>>>>>>>>>>>>r<<<<<<<<<<<<<<<<<<<<---r<<<<<<<<<<<<<<<<<<<<<<<<<<l>>>>>>>>>>>>>>>>>>>>>>f>>>>>>>>>>
    ---------------M-----------XXXXXXXXX---->>>>>>>>>>>>>>>l>>>>>>>>>>>>>>\\\\\\\\----------g<<----<<<<<<<<----<<<<<<<<p-----------------p-p---l-----p-----------P-ggXf----------
    ---------------------------XX{XX--XX-----------ggg-----l-----------ggr\\\\\\\\>>>>>>>>>>><<<<<<<<----<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>l<<<<<<<<<<<<<<<<<<<<<<f<<<<<<<<<<
    ------------------------r--XXXXXXXXX--------p----ggg---l----r-------gg\\\\\\\\---------B-<<<<<<<<<<<<<<--r-<<<<<<<<r--------p--------------l---------------p------f----------
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>}>>>>>>>>>>>>>>>>>>>>l<<<<<<<<<<<<<<<<<<<<<<-----------<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>l<<<<<<<<<<<<<<<<<<<<<<f<<<<<<<<<<

  default_tile: MetalFloor

# Messages can be up to 14 chars (15 if there is a follow-on screen) and must have 4+ spaces between them.
# - '0123456789012345'
messages:
  - "Sorting room "